" Load Plugins first as some options depend on them later
execute 'source' "~/.config/vim/plugins.vim"

" Then the rest
for file in split(glob("~/.config/vim/vimrc.d/*.vim"), '\n')
	execute 'source' file
endfor
